apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-springboot
  template:
    metadata:
      labels:
        app: cicd-springboot
    spec:
      containers:
        - name: springboot
          image: moebadarneh/cicd-docker-demo:cicd-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cicd-springboot
